### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by mnchase** [sidharthanup/Audio-Analyzer-and-Transcription-Tool#24]
How do we want to handle output?  Create a file and send it to the front end with save possibility?  Automatically save and send only a snippit to frontend?

**Comment by rphill299** [comment]
We have different cases to handle.

In the single file case, my vote is for a checkbox, if checked, then the output is saved to a file.  If unchecked, don't save it.  In either case, the text is displayed to the user.

In the folder case, my vote is that I force the checkbox to be checked, so that the outputs are all saved to a similar "outputs" folder.  Displaying this text would require some UI magic to somehow have a tabbed view of the text or something, which I think is less important.

**Comment by rphill299** [comment]
See #35 and open new issue if anything needs changed
